services:
  app-restaurante:
    # image: app-restaurante
    # container_name: app-restaurante-container
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-restaurante-container
    ports:
      - "8080:8080"
    networks:
      - app-restaurante-network
    depends_on:
      # - postgres
      postgres:
        condition: service_healthy # esepera que postgres este bien para utilizar
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: postgres_restaurante
    environment:
      POSTGRES_PASSWORD: 2005
      POSTGRES_DB: restaurante_db
      POSTGRES_USER: alejandro
    ports:
      - "5433:5432"
    networks:
      - app-restaurante-network
    volumes:
      - postgres-volume-restaurante:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alejandro -d restaurante_db"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

networks:
  app-restaurante-network:
volumes:
  postgres-volume-restaurante:
