services:
  app-restaurante:
    image: alejo224j/sistemarestaurante-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-restaurante-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PORT: ${SPRING_PORT}
    networks:
      - app-restaurante-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./:/app
      - restaurante_uploads:/app/uploads
    working_dir: /app
    command: ./mvnw spring-boot:run

  postgres:
    image: postgres
    container_name: postgres_restaurante
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - app-restaurante-network
    volumes:
      - postgres-volume-restaurante:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  app-restaurante-network:

volumes:
  postgres-volume-restaurante:
  restaurante_uploads:
